services:
  - type: web
    name: client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: ".*"
        destination: "/index.html"
