services:
  - type: web
    name: client
    env: static
    buildCommand: npm run build
    startCommand: serve -s build
    routes:
      - src: /static/**
        dest: /static
      - src: /favicon.ico
        dest: /favicon.ico
      - src: /manifest.json
        dest: /manifest.json
      - src: /logo192.png
        dest: /logo192.png
      - src: /logo512.png
        dest: /logo512.png
      - src: /robots.txt
        dest: /robots.txt
      - src: /index.html
        dest: /index.html
      - src: /*
        dest: /index.html
